/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CustomPicker: typeof import('./src/components/custom/customPicker/index.vue')['default']
    CustomTabs: typeof import('./src/components/custom/customTabs/index.vue')['default']
    Empty: typeof import('./src/components/common/empty/index.vue')['default']
    Gap: typeof import('./src/components/common/gap/index.vue')['default']
    Help: typeof import('./src/components/help/index.vue')['default']
    ImageUpload: typeof import('./src/components/common/imageUpload/index.vue')['default']
    InputNumber: typeof import('./src/components/common/inputNumber/index.vue')['default']
    Modal: typeof import('./src/components/common/modal/index.vue')['default']
    Node: typeof import('./src/components/common/richText/node/node.vue')['default']
    Picture: typeof import('./src/components/common/picture/index.vue')['default']
    PullToRefresh: typeof import('./src/components/pullToRefresh/index.vue')['default']
    RefreshList: typeof import('./src/components/refreshList/index.vue')['default']
    RichText: typeof import('./src/components/common/richText/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Segmented: typeof import('./src/components/common/segmented/index.vue')['default']
    SignInImageUpload: typeof import('./src/components/custom/signInImageUpload/index.vue')['default']
    Stepper: typeof import('./src/components/common/stepper/index.vue')['default']
    Textarea: typeof import('./src/components/common/textarea/index.vue')['default']
    Video: typeof import('./src/components/common/video/index.vue')['default']
  }
}
