/*
 * @Author: huangpengfei 784667332@qq.com
 * @Date: 2023-11-21 18:04:45
 * @LastEditors: huangpengfei 784667332@qq.com
 * @LastEditTime: 2023-11-24 09:18:50
 * @FilePath: /uniapp_template/components.d.ts
 * @Description:
 *
 * Copyright (c) 2023 by 784667332@qq.com, All Rights Reserved.
 */
/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {};

declare module '@vue/runtime-core' {
    export interface GlobalComponents {
        CustomPicker: typeof import('./src/components/custom/customPicker/index.vue')['default'];
        CustomTabs: typeof import('./src/components/custom/customTabs/index.vue')['default'];
        Empty: typeof import('./src/components/common/empty/index.vue')['default'];
        Gap: typeof import('./src/components/common/gap/index.vue')['default'];
        Help: typeof import('./src/components/help/index.vue')['default'];
        ImageUpload: typeof import('./src/components/imageUpload/index.vue')['default'];
        InputNumber: typeof import('./src/components/common/inputNumber/index.vue')['default'];
        Modal: typeof import('./src/components/common/modal/index.vue')['default'];
        Node: typeof import('./src/components/common/richText/node/node.vue')['default'];
        Picture: typeof import('./src/components/common/picture/index.vue')['default'];
        PullToRefresh: typeof import('./src/components/pullToRefresh/index.vue')['default'];
        RefreshList: typeof import('./src/components/refreshList/index.vue')['default'];
        RichText: typeof import('./src/components/common/richText/index.vue')['default'];
        Segmented: typeof import('./src/components/common/segmented/index.vue')['default'];
        Stepper: typeof import('./src/components/common/stepper/index.vue')['default'];
        Tabbar: typeof import('./src/components/tabbar/index.vue')['default'];
        Textarea: typeof import('./src/components/common/textarea/index.vue')['default'];
        Video: typeof import('./src/components/common/video/index.vue')['default'];
    }
}
