/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Ellipsis: typeof import('./src/components/common/ellipsis/Ellipsis.vue')['default']
    Help: typeof import('./src/components/help/Help.vue')['default']
    ImageUpload: typeof import('./src/components/common/imageUpload/ImageUpload.vue')['default']
    Node: typeof import('./src/components/common/richText/node/node.vue')['default']
    Poster: typeof import('./src/components/common/poster/Poster.vue')['default']
    PullToRefresh: typeof import('./src/components/common/pullToRefresh/PullToRefresh.vue')['default']
    RefreshList: typeof import('./src/components/common/refreshList/RefreshList.vue')['default']
    RichText: typeof import('./src/components/common/richText/RichText.vue')['default']
  }
}
